baseurl: /radxa123
permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: itfanr
  email: bjq1016@126.com
  link: http://my.oschina.net/itfanr
  weibo: http://weibo.com/itfan
  github: http://github.com/itfanr

# 站点信息
title: radxa入门汇总
description: raxda开发板的相关资料等汇总
url: http://itfanr.github.io/radxa123
rss_url: radxa123/pages/atom.xml

# gavatar头像及Favicon
gavatar: http://itfanr.qiniudn.com/2014-12-28-gavatar.jpg
favicon: http://itfanr.qiniudn.com/2014-12-28-favicon.ico

# disqus 设置
disqus:
  shortname: radxa123

# 主题设置，自动激活某个标签
active: 入门

# 首页除了最新文章外显示分类
cates: 
  - 入门
  - 创意 


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
